import jsPDF from 'jspdf';

interface PDFReportData {
  title: string;
  scenario: string;
  completionDate: string;
  conversationHistory: Array<{
    role: string;
    content: string;
    speaker?: string;
  }>;
  score?: number;
  maxScore?: number;
  feedback?: string;
  outcome?: string;
}

export const generatePDFReport = (data: PDFReportData): void => {
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica');
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(44, 62, 80);
  doc.text(data.title, 20, 30);
  
  // Scenario info
  doc.setFontSize(14);
  doc.setTextColor(52, 73, 94);
  doc.text(`Scenario: ${data.scenario}`, 20, 50);
  doc.text(`Completed: ${data.completionDate}`, 20, 60);
  
  // Score if available
  if (data.score !== undefined && data.maxScore !== undefined) {
    doc.setFontSize(16);
    doc.setTextColor(46, 204, 113);
    doc.text(`Score: ${data.score}/${data.maxScore}`, 20, 80);
  }
  
  // Outcome if available
  if (data.outcome) {
    doc.setFontSize(14);
    doc.setTextColor(52, 152, 219);
    doc.text(`Outcome: ${data.outcome}`, 20, 90);
  }
  
  // Feedback if available
  let feedbackLines: string[] = [];
  if (data.feedback) {
    doc.setFontSize(12);
    doc.setTextColor(44, 62, 80);
    doc.text('Feedback:', 20, 110);
    
    // Split feedback into lines that fit the page
    feedbackLines = doc.splitTextToSize(data.feedback, 170);
    doc.setFontSize(10);
    doc.setTextColor(52, 73, 94);
    doc.text(feedbackLines, 20, 120);
  }
  
  // Conversation History
  let yPosition = feedbackLines.length > 0 ? 120 + (feedbackLines.length * 5) + 20 : 140;
  
  doc.setFontSize(14);
  doc.setTextColor(44, 62, 80);
  doc.text('Conversation History:', 20, yPosition);
  
  yPosition += 10;
  
  // Add conversation history
  data.conversationHistory.forEach((message, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    
    const speaker =
      message.role === "assistant"
        ? "Interviewer"
        : message.speaker || message.role;
    const content = message.content;
    
    // Speaker name
    doc.setFontSize(12);
    doc.setTextColor(52, 152, 219);
    doc.text(`${speaker}:`, 20, yPosition);
    
    yPosition += 5;
    
    // Message content
    doc.setFontSize(10);
    doc.setTextColor(44, 62, 80);
    const contentLines = doc.splitTextToSize(content, 170);
    doc.text(contentLines, 25, yPosition);
    
    yPosition += contentLines.length * 5 + 5;
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(149, 165, 166);
  doc.text('Generated by SpeakGrade Lite', 20, 280);
  
  // Save the PDF
  doc.save(`${data.scenario.replace(/\s+/g, '_')}_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
